name: rhymesayers
favicon: null
layout_spectrum: 0.43812617543153465
typography_spectrum: 0.41391793196089566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9162524449639022
  lightness: 0.0023314813151955605
  saturation: 0.06970396731048822
  rhythmicContrast: 0.7303804806433618
purpose: []
